# Generated by Django 5.0.1 on 2025-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fee_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(default='avatars/avatar.svg', upload_to='avatars/')),
                ('dom', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=100, null=True)),
                ('parents_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('parents_name', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
